name: Update Image Gallery

on:
  push:
    paths:
      - '*.gif'
      - '*.png'
      - '*.jpg'

jobs:
  update-gallery:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          npm install -g @actions/github
          npm install @octokit/rest

      - name: Generate images.json with dates
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          node -e "
            const fs = require('fs');
            const { Octokit } = require('@octokit/rest');
            const octokit = new Octokit({ auth: process.env.GITHUB_TOKEN });

            console.log('Starting script...');

            async function getFileCreationDate(owner, repo, path) {
              try {
                console.log('Fetching commit date for:', path);
                const commits = await octokit.repos.listCommits({
                  owner,
                  repo,
                  path,
                  per_page: 1,
                });
                if (commits.data.length > 0) {
                  console.log('Commit date found:', commits.data[0].commit.committer.date);
                  return commits.data[0].commit.committer.date;
                }
                console.log('No commits found, using current date');
                return new Date().toISOString();
              } catch (error) {
                console.error('Error fetching commit date for', path, error.message);
                return new Date().toISOString();
              }
            }

            (async () => {
              try {
                console.log('Reading files...');
                const files = fs.readdirSync('.')
                  .filter(f => /\.(gif|png|jpg)$/i.test(f))
                  .map(f => ({
                    url: 'https://raw.githubusercontent.com/Endermanik13/PokkiSite/main/' + f,
                    name: f
                  }));

                console.log('Files found:', files);

                if (files.length === 0) {
                  console.log('No image files found, creating empty images.json');
                  fs.writeFileSync('images.json', JSON.stringify([], null, 2));
                  return;
                }

                const filesWithDates = [];
                for (const file of files) {
                  console.log('Processing file:', file.name);
                  const date = await getFileCreationDate('Endermanik13', 'PokkiSite', file.name);
                  filesWithDates.push({
                    url: file.url,
                    date: date
                  });
                }

                console.log('Sorting files by date...');
                filesWithDates.sort((a, b) => new Date(b.date) - new Date(a.date));

                console.log('Writing to images.json:', filesWithDates);
                fs.writeFileSync('images.json', JSON.stringify(filesWithDates, null, 2));
              } catch (error) {
                console.error('Error in script:', error.message);
                process.exit(1);
              }
            })();
          "

      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add images.json
          git commit -m "Update images.json with new gallery files and dates" || echo "No changes to commit"
          git push
